#!/usr/bin/env python3
"""
Graphics manager - bridge between IDE (.gfx.json) and build (gfxdata.h).

Usage:
  gfxmanager to-header <input.gfx.json> -o <output.h>   # JSON -> C header
  gfxmanager from-header <input.h> -o <output.gfx.json> # C header -> JSON (for IDE load)

.gfx.json format (native, IDE-friendly):
  {
    "palette": [0, 128, 240, ...],   # 32 bytes, 3-3-2 RGB
    "tiles": [[[0,1,...], ...], ...] # 64 tiles, each 16×16, values 0-3
  }
  Legacy: "tiles" as base64 string (ROM format) also accepted for to-header.
"""

import argparse
import base64
import json
import re
import sys
from pathlib import Path


PALETTE_SIZE = 32
TILE_COUNT = 64
BYTES_PER_TILE = 64
TILES_SIZE = TILE_COUNT * BYTES_PER_TILE
PLANE_SIZE = 2048


def plane_byte_idx(x: int, y: int) -> int:
    """MAME scramble_spritelayout: 4 blocks [TL, TR, BL, BR]"""
    return (y & 7) + (8 if x >= 8 else 0) + (16 if y >= 8 else 0)


def decode_rom_tile(bytes_data: bytes, tile_index: int) -> list[list[int]]:
    p0_base = tile_index * 32
    p1_base = PLANE_SIZE + tile_index * 32
    px = []
    for y in range(16):
        row = []
        for x in range(16):
            bi = plane_byte_idx(x, y)
            bit = 7 - (x & 7)
            p0 = (bytes_data[p0_base + bi] >> bit) & 1
            p1 = (bytes_data[p1_base + bi] >> bit) & 1
            row.append(p0 | (p1 << 1))
        px.append(row)
    return px


def encode_rom_tile(px: list[list[int]]) -> bytes:
    out = bytearray(64)
    for y in range(16):
        for x in range(16):
            p = px[y][x] & 3
            bi = plane_byte_idx(x, y)
            bit = 7 - (x & 7)
            if p & 1:
                out[bi] |= 1 << bit
            if p & 2:
                out[32 + bi] |= 1 << bit
    return bytes(out)


def parse_hex_bytes(s: str) -> list[int]:
    """Parse C-style hex bytes: 0x00,0x80,0xf0,..."""
    out = []
    for m in re.finditer(r"0x([0-9a-fA-F]{2})", s):
        out.append(int(m.group(1), 16))
    return out


def read_gfxdata_h(path: Path) -> tuple[list[int], bytes]:
    """Parse gfxdata.h, return (palette[32], tiles_bytes[4096])."""
    text = path.read_text()
    palette = []
    tiles_raw = []

    # Palette: parse only from data (skip __at(0x5000) etc)
    pal_start = text.find("palette[32]")
    tilerom_start = text.find("tilerom[0x1000]")
    if pal_start >= 0 and tilerom_start > pal_start:
        chunk = text[pal_start:tilerom_start]
        # Skip to first data line (after " = {")
        data_start = chunk.find(" = {")
        if data_start >= 0:
            palette = parse_hex_bytes(chunk[data_start:])

    # Tiles: parse only from data (skip __at(0x4000) tilerom[0x1000] etc)
    if tilerom_start >= 0:
        chunk = text[tilerom_start:]
        # Skip to opening brace, then parse all hex after that
        brace_start = chunk.find(" = {")
        if brace_start >= 0:
            tiles_raw = parse_hex_bytes(chunk[brace_start:])
        else:
            tiles_raw = parse_hex_bytes(chunk)

    if len(palette) < PALETTE_SIZE:
        palette.extend([0] * (PALETTE_SIZE - len(palette)))
    palette = palette[:PALETTE_SIZE]
    if len(tiles_raw) < TILES_SIZE:
        tiles_raw = list(tiles_raw) + [0] * (TILES_SIZE - len(tiles_raw))
    tiles_bytes = bytes(tiles_raw[:TILES_SIZE])
    return palette, tiles_bytes


def write_gfxdata_h(path: Path, palette: list[int], tiles: bytes) -> None:
    """Write gfxdata.h with palette and tiles."""
    path.parent.mkdir(parents=True, exist_ok=True)

    def fmt_palette() -> str:
        lines = []
        for i in range(0, PALETTE_SIZE, 8):
            chunk = palette[i : i + 8]
            lines.append(",".join(f"0x{b:02x}" for b in chunk))
        return ",\n  ".join(lines)

    def fmt_tiles() -> str:
        lines = []
        for i in range(0, TILES_SIZE, 16):
            chunk = tiles[i : i + 16]
            lines.append(",".join(f"0x{b:02x}" for b in chunk))
        return ",".join(lines)

    out = f"""/* Generated by gfxmanager - do not edit */
/* galaxold_spritelayout: 64 tiles 16×16 2bpp, plane0 0-2047, plane1 2048-4095 */

const char __at (0x5000) palette[32] = {{/*{{pal:332,n:4}}*/
  {fmt_palette()}
}};

const char __at (0x4000) tilerom[0x1000] = {{/*{{w:16,h:16,np:2,count:64}}*/
{fmt_tiles()}
}};
"""
    path.write_text(out)


def cmd_to_header(args: argparse.Namespace) -> int:
    """Convert .gfx.json to gfxdata.h."""
    data = json.loads(args.input.read_text())
    palette = data.get("palette", [])
    if len(palette) < PALETTE_SIZE:
        palette.extend([0] * (PALETTE_SIZE - len(palette)))
    palette = palette[:PALETTE_SIZE]

    tiles_data = data.get("tiles", "")
    if isinstance(tiles_data, list):
        tiles = native_tiles_to_rom_bytes(tiles_data)
    else:
        tiles = base64.b64decode(tiles_data) if tiles_data else bytes(TILES_SIZE)
    if len(tiles) < TILES_SIZE:
        tiles = tiles + bytes(TILES_SIZE - len(tiles))
    tiles = tiles[:TILES_SIZE]

    out_path = Path(args.output)
    write_gfxdata_h(out_path, palette, tiles)
    print(f"Wrote {out_path}", file=sys.stderr)
    return 0


def native_tiles_to_rom_bytes(native_tiles: list) -> bytes:
    out = bytearray(TILES_SIZE)
    for t in range(min(TILE_COUNT, len(native_tiles))):
        nt = native_tiles[t]
        if not nt or not isinstance(nt, list):
            continue
        pad = [[(nt[y][x] & 3) if y < len(nt) and isinstance(nt[y], list) and x < len(nt[y]) else 0 for x in range(16)] for y in range(16)]
        enc = encode_rom_tile(pad)
        for i in range(32):
            out[t * 32 + i] = enc[i]
        for i in range(32):
            out[PLANE_SIZE + t * 32 + i] = enc[32 + i]
    return bytes(out)


def cmd_from_header(args: argparse.Namespace) -> int:
    """Convert gfxdata.h to .gfx.json (decoded tiles for IDE)."""
    palette, tiles_bytes = read_gfxdata_h(Path(args.input))
    native_tiles = []
    for t in range(TILE_COUNT):
        native_tiles.append(decode_rom_tile(tiles_bytes, t))
    data = {"palette": palette, "tiles": native_tiles}
    out_path = Path(args.output)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(json.dumps(data, indent=2))
    print(f"Wrote {out_path}", file=sys.stderr)
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description="Graphics manager for Galaxian BASIC")
    sub = parser.add_subparsers(dest="cmd", required=True)

    to_h = sub.add_parser("to-header", help="Convert .gfx.json to gfxdata.h")
    to_h.add_argument("input", type=Path, help="Input .gfx.json")
    to_h.add_argument("-o", "--output", required=True, help="Output .h file")
    to_h.set_defaults(func=cmd_to_header)

    from_h = sub.add_parser("from-header", help="Convert gfxdata.h to .gfx.json")
    from_h.add_argument("input", type=Path, help="Input gfxdata.h")
    from_h.add_argument("-o", "--output", required=True, help="Output .gfx.json")
    from_h.set_defaults(func=cmd_from_header)

    args = parser.parse_args()
    # Normalize input to Path for from-header
    if args.cmd == "to-header":
        args.input = Path(args.input)
    elif args.cmd == "from-header":
        args.input = Path(args.input)
    return args.func(args)


if __name__ == "__main__":
    sys.exit(main())
